services:
  db:
    image: postgres:12.19-alpine3.19
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    restart: always

  redis:
      container_name: 'redis'
      image: 'redis'
      ports:
        - '0.0.0.0:6379:6379'
      volumes:
        - 'redis_data:/data'
      restart: always

volumes:
  postgres_data:
  rabbit_data:
  redis_data: