# Generated by Django 5.0.3 on 2024-05-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('overdue', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('overdue', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
